### ISSUE TITLE
"Testers wanted/sought" - addition to the main README.md?

### ISSUE THREAD

**Issue by ghost** [gobolinux/AlienVFS#2]
Hello lucas,

I was wondering after http://lists.gobolinux.org/pipermail/gobolinux-users/2017-December/009905.html, perhaps it may also be useful to add a subsection entry to the main README for AlienVFS, that people could/should help test AlienVFS on other distributions?

For example, a new subsection perhaps in README.md that people should test AlienVFS; and perhaps they can also help test which dependencies are required, e. g. the table at https://github.com/gobolinux/AlienVFS#dependencies - anyway just an idea. Also happy upcoming xmas holidays and new year's eve to all oldschool GoboLinux devs in general! :)

**Comment by lucasvr** [comment]
I ended up doing the port and initial testing on Fedora by myself. The README.md now features a table with dependencies and build instructions that should be enough to get one started. 

Thanks and happy xmas for you too!
